server:
  port: 8090
spring:
  ############  JDBC配置  ###################
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fr_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    ########### Druid 连接池配置  #############
    #连接池配置
    #Spring Boot中默认支持的连接池有dbcp,dbcp2, tomcat, hikari三种连接池,故需要特殊定制
    initialSize: 5
    minIdle: 5
    maxActive: 20
    validationQuery: SELECT 'x' FROM DUAL
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #当连接空闲时，是否执行连接测试
    testWhileIdle: true
    #当从连接池借用连接时，是否测试该连接
    testOnBorrow: false
    #在连接归还到连接池时是否测试该连接
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #监控统计用的filter:stat日志用的filter:log4j2防御sql注入的filter:wall
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


